name: fixit
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  cached_network_image: ^3.3.0
  cloud_firestore: ^4.13.6
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^5.4.0
  file_picker: ^6.1.1
  firebase_auth: ^4.15.3
  firebase_core: ^2.24.2
  firebase_crashlytics: ^3.4.8
  firebase_storage: ^11.5.6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  flutter_map: ^6.1.0
  flutter_screenutil: ^5.9.0
  flutter_staggered_grid_view: ^0.7.0
  freezed_annotation: ^2.4.1
  geocoding: ^2.1.1
  geolocator: ^10.1.0
  get_it: ^7.6.4
  go_router: ^12.1.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.18.1
  json_annotation: ^4.8.1
  latlong2: ^0.9.0
  logger: ^2.0.2+1
  oktoast: ^3.4.0

dev_dependencies:
  bloc_test: ^9.1.5
  build_runner: ^2.4.7
  fake_cloud_firestore: ^2.4.7
  firebase_auth_mocks: ^0.13.0
  firebase_storage_mocks: ^0.6.1
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.4.5
  hive_generator: ^2.0.1
  http_mock_adapter: ^0.6.1
  json_serializable: ^6.7.1
  lints: ^3.0.0
  mockito: ^5.4.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 900
